### ISSUE TITLE
テーマを更新すると wp-content/themes 配下のテーマのルートフォルダ名が変更される。

### ISSUE THREAD

**Issue by kusokamayarou** [getshifter/shifter-install-helper#12]
プラグインを利用して、テーマをインストールし、テーマを更新したところ、wp-content/themes 配下のテーマのルートフォルダ名が変更されました。特に、テーマの更新の手順に特別なことはしていません。

- 更新前 : shifter-github-hosting-theme-sample_test
- 更新後 : 8cf94100-ece6-11ea-956f-e7c91416871d-P70KfV

- WordPress テーマ
    - [getshifter/shifter\-github\-hosting\-theme\-sample](https://github.com/getshifter/shifter-github-hosting-theme-sample) をコピーし、テーマ名やリポジトリ名を変更
    - リポジトリ名 : shifter-github-hosting-theme-sample_test
    - リポジトリは、プライベート
    - リリースパッケージ は、以下の手順にて、GitHub Actions で自動作成。
    - [Shifter Github Plugin/Theme Installer を使って自作テーマ・プラグインをアップデートしよう \#JP\_Getshifter \| Gatespace's Blog](https://gatespace.jp/2019/12/02/shifter-github-plugin-theme-installer-use-sample/)

デフォルトでインストールされているテーマ等は、更新しても、フォルダ名が変更されないので、何がしかプラグインでのインストールが影響しているのかなと思ったのですが、対応を教えていただけると助かります。

- ![FireShot Capture 487 - WP File Manager ‹ 現場クラウド Conne — WordPress_ - 061f3c47-2b86-4766-bcdc-abff94590a90 app getshifter io](https://user-images.githubusercontent.com/25380796/91941117-a5dc1380-ed33-11ea-83cb-cde4520b77f4.png)

- ![FireShot Capture 490 - WP File Manager ‹ 現場クラウド Conne — WordPress_ - 061f3c47-2b86-4766-bcdc-abff94590a90 app getshifter io](https://user-images.githubusercontent.com/25380796/91941129-aa083100-ed33-11ea-84c0-0b2c52a592bf.png)

---
- style.css

```
/*!
Theme Name: Shifter GitHub hosting theme sample
Theme URI: http://underscores.me/
Author: Shifter Team
Author URI: http://underscores.me/
Description: Custom theme: Shifter GitHub hosting theme sample, developed by Shifter Team
Version: {release version}
License: GNU General Public License v2 or later
License URI: LICENSE
Text Domain: sample_theme
Tags: custom-background, custom-logo, custom-menu, featured-images, threaded-comments, translation-ready

This theme, like WordPress, is licensed under the GPL.
Use it to make something cool, have fun, and share what you've learned with others.

Shifter GitHub hosting theme sample is based on Underscores https://underscores.me/, (C) 2012-2017 Automattic, Inc.
Underscores is distributed under the terms of the GNU GPL v2 or later.

Normalizing styles have been helped along thanks to the fine work of
Nicolas Gallagher and Jonathan Neal https://necolas.github.io/normalize.css/
*/
```

---
- release.yml

```
# Workflow Document: https://help.github.com/en/articles/workflow-syntax-for-github-actions

# This workflow detects a tag push to Github, it will automatically upload the package to github releases.
name: release

# see: https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  create:
    tags:
    # - v*.*.*  # to use filters. wildcard characters supported.

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobs
jobs:
  release:
    name: Release

    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:

    # [official action] clone code to workspace
    # https://github.com/actions/checkout
    - uses: actions/checkout@v1

    # install modules by composer. remove this step it if no needed.
    # - name: composer install
    #   run: composer install

    # install modules by npm.
    # - name: npm clean install
    #   run: npm ci

    # remove this step if you want to update the version manually.
    # NOTICE: ref_type exists only for events of type create. see https://developer.github.com/v3/activity/events/types/#createevent
    - name: add version
      run: |
        # retrieve tag and replase version number in file.
        export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
        sed -i -e "s/{release version}/${TAGNAME}/g" style.css

    # create zip acrive for install to WordPress.
    # please edit FILES_TO_ARCIVE to suit your project.
    - name: create archive
      env:
        PACKAGE_NAME: "shifter-github-hosting-theme-sample_test_0001"
        FILES_TO_ARCIVE: "*"
      run: zip -r ${PACKAGE_NAME}.zip ${FILES_TO_ARCIVE}

    # upload zip arvive by ghr.
    # `secrets.GITHUB_TOKEN` for using ghr is issued temporarily when executing action. No special settings are required.
    # ghr - Easily ship your project to your user using Github Releases : https://deeeet.com/ghr/
    - name: upload
      env:
        PACKAGE_NAME: "shifter-github-hosting-theme-sample_test_0001"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /home/runner/go
      run: |
        # retrieve tag and replase version number in file.
        export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
        # install ghr, then upload archve.
        go get -u github.com/tcnksm/ghr
        ${GOPATH}/bin/ghr -b "${PACKAGE_NAME} ${TAGNAME}" -replace ${TAGNAME} ${PACKAGE_NAME}.zip
```
